# this action tests that minimal possible semver versions are correct,
# if it fails, there's probably minimal dependency version needs to be bumped
name: minimal-dep-check-ignore-this

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
         - nightly

    steps:
     - uses: actions/checkout@v3
     - uses: dtolnay/rust-toolchain@nightly
     - run: cargo +nightly -Z minimal-versions update && cargo +nightly test --no-default-features --features linkify
